# Generated by Django 4.0.6 on 2022-07-12 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_remove_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Images',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
