# Generated by Django 4.0.6 on 2022-07-17 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_alter_comment_comment_alter_comment_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='rate',
            field=models.IntegerField(default=5),
        ),
    ]
