# Generated by Django 4.0.6 on 2022-07-12 15:29

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('keyword', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=50)),
                ('workinghours', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=100)),
                ('contactcomment', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('whatsappcontact', models.CharField(blank=True, max_length=15)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('aboutus', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('contactaddress', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('smtpserver', models.CharField(blank=True, max_length=20)),
                ('smtpemail', models.CharField(blank=True, max_length=20)),
                ('smtppassword', models.CharField(blank=True, max_length=10)),
                ('smtpport', models.CharField(blank=True, max_length=5)),
                ('icon', models.ImageField(blank=True, upload_to='images/')),
                ('facebook', models.CharField(blank=True, max_length=50)),
                ('instagram', models.CharField(blank=True, max_length=50)),
                ('twitter', models.CharField(blank=True, max_length=50)),
                ('youtube', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=10)),
                ('team1', models.CharField(blank=True, max_length=50)),
                ('team2', models.CharField(blank=True, max_length=50)),
                ('team3', models.CharField(blank=True, max_length=50)),
                ('position1', models.CharField(blank=True, max_length=50)),
                ('position2', models.CharField(blank=True, max_length=50)),
                ('position3', models.CharField(blank=True, max_length=50)),
                ('sliderbig1', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('sliderbig2', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('sliderbig3', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('slidersmall1', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('slidersmall2', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('slidersmall3', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
