# Generated by Django 4.0.6 on 2022-07-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='img_team1',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='setting',
            name='img_team2',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='setting',
            name='img_team3',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
