# Generated by Django 4.0.6 on 2022-07-15 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='adminnone',
            new_name='adminnote',
        ),
    ]
